on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml
  release:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Get  with Maven
      id: version
      run: |
        set -e
        task_processor_version=$(grep "<task-processor.version>" pom.xml | grep -v '<!--' | sed -E 's/.*<task-processor.version>([^<]+)<\/task-processor.version>.*/\1/')
        [ -z "$task_processor_version" ] && echo "Failed to extract task-processor.version from pom.xml" && exit 1
        
        release_version="v${task_processor_version}"
        if gh release view "$release_version" > /dev/null; then
          release_version="${release_version}-${{ github.run_number }}"
        fi
        
        echo "number=$release_version" | tee $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      run: |
        gh release create ${{ env.VERSION }} -t "Release ${{ env.VERSION }}" -n "Release ${{ env.VERSION }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ steps.version.outputs.number }}